import type { Collection } from 'tinacms';
import {
  brandColorSchemeOptions,
  brandFontPresetOptions,
  googleFontOptions,
  headerStyleOptions,
  layoutCornerOptions,
  layoutSpacingOptions,
  layoutWidthOptions,
  logoModeOptions,
  logoShapeOptions,
} from '../../src/config/brand';

const brandColourSwatches = [
  '#F5F1E8',
  '#FAF7EF',
  '#2F7D6D',
  '#4A9D8D',
  '#2563EB',
  '#F97316',
  '#8A3FFC',
  '#E11D48',
  '#22C55E',
  '#26342F',
  '#1E293B',
  '#101818',
  '#D28A50',
  '#E0A36E',
  '#FFFFFF',
  '#000000',
];

const colourField = (name: string, label: string, description: string) => ({
  type: 'string' as const,
  name,
  label,
  description,
  ui: { component: 'color' },
  colorFormat: 'hex',
  widget: 'sketch' as const,
  colors: brandColourSwatches,
});

const optionalGoogleFontOptions = [
  { value: '', label: 'Use selected font pairing' },
  ...googleFontOptions,
];

const siteSettingsCollection: Collection = {
  name: 'siteSettings',
  label: 'Site Settings',
  path: 'src/content/site_settings',
  format: 'json',
  ui: {
    allowedActions: {
      create: false,
      delete: false,
    },
    global: true,
  },
  fields: [
    {
      type: 'string',
      name: 'title',
      label: 'Title (internal)',
      isTitle: true,
      required: true,
    },
    { type: 'string', name: 'location', label: 'Location', required: true },
    { type: 'string', name: 'contact_intro', label: 'Contact Intro', ui: { component: 'textarea' }, required: true },
    { type: 'string', name: 'footer_note', label: 'Footer Note', ui: { component: 'textarea' }, required: true },
    {
      type: 'object',
      name: 'brand',
      label: 'Brand Settings',
      fields: [
        {
          type: 'string',
          name: 'color_scheme',
          label: 'Colour Scheme',
          description: 'Start with a complete palette. Choose Custom Colours only when you want the individual colour fields below to control the site.',
          options: brandColorSchemeOptions,
          required: true,
        },
        {
          type: 'string',
          name: 'logo_mode',
          label: 'Logo Style',
          description: 'Use text for the simplest setup, initials for a generated mark, or image once you upload a real logo.',
          options: logoModeOptions,
          required: true,
        },
        { type: 'string', name: 'logo_text', label: 'Logo Text', description: 'Shown as the wordmark and fallback alt text.', required: true },
        { type: 'string', name: 'logo_initials', label: 'Logo Initials', description: 'Used when Logo Style is set to Initials mark.' },
        {
          type: 'string',
          name: 'logo_shape',
          label: 'Initials Shape',
          options: logoShapeOptions,
          required: true,
        },
        {
          type: 'image',
          name: 'logo_image_light',
          label: 'Logo Image (Light Surfaces)',
          description: 'Optional logo asset used on light backgrounds. Stored from /public/images.',
        },
        {
          type: 'image',
          name: 'logo_image_dark',
          label: 'Logo Image (Dark Surfaces)',
          description: 'Optional logo asset used on dark backgrounds. Stored from /public/images.',
        },
        {
          type: 'string',
          name: 'font_preset',
          label: 'Site Font Pairing',
          description: 'Fastest option for beginners. Pick a complete heading, body, hero, and logo font set.',
          options: brandFontPresetOptions,
          required: true,
        },
        {
          type: 'string',
          name: 'heading_font',
          label: 'Heading Font Override',
          description: 'Optional. Leave this as the pairing default unless you want a specific heading font.',
          options: optionalGoogleFontOptions,
          ui: { component: 'fontPreviewSelect' },
        },
        {
          type: 'string',
          name: 'body_font',
          label: 'Body Font Override',
          description: 'Optional. This controls paragraphs, buttons, badges, and most interface text.',
          options: optionalGoogleFontOptions,
          ui: { component: 'fontPreviewSelect' },
        },
        {
          type: 'string',
          name: 'hero_font',
          label: 'Hero Heading Font Override',
          description: 'Optional. This is the default font used by hero slider headings.',
          options: optionalGoogleFontOptions,
          ui: { component: 'fontPreviewSelect' },
        },
        {
          type: 'string',
          name: 'logo_font',
          label: 'Logo Text Font',
          description: 'Choose the font used when the logo is rendered as text.',
          options: googleFontOptions,
          ui: { component: 'fontPreviewSelect' },
          required: true,
        },
        {
          type: 'object',
          name: 'colors',
          label: 'Colour Tokens',
          fields: [
            colourField('primary', 'Canvas', 'Pick the main page background colour.'),
            colourField('primary_soft', 'Canvas Soft', 'Used in gradients and softer light surfaces.'),
            colourField('accent', 'Accent', 'Primary accent for links, dividers, and key UI moments.'),
            colourField('accent_light', 'Accent Light', 'Hover and lighter accent variant.'),
            colourField('text', 'Text', 'Primary body text colour.'),
            colourField('muted', 'Muted Text', 'Secondary text and metadata colour.'),
            colourField('surface', 'Surface', 'Card and panel background colour.'),
            colourField('surface_alt', 'Surface Alt', 'Alternate section and card background colour.'),
            colourField('border', 'Border', 'Border and rule colour.'),
            colourField('champagne', 'Heading Ink', 'Used for strong headline text and emphasis.'),
            colourField('ink', 'Primary Button Ink', 'Dark solid button and deep UI colour.'),
            colourField('dark_surface', 'Dark Surface', 'Main dark-theme section background colour.'),
            colourField('dark_surface_alt', 'Dark Surface Alt', 'Alternate dark background colour.'),
            colourField('dark_border', 'Dark Border', 'Border colour for dark sections.'),
            colourField('dark_accent', 'Dark Accent', 'Accent used on dark sections and dark hero states.'),
            colourField('dark_accent_light', 'Dark Accent Light', 'Hover and lighter accent for dark sections.'),
          ],
        },
      ],
    },
    {
      type: 'object',
      name: 'layout',
      label: 'Layout Settings',
      description: 'Basic site-wide layout choices. These are safe starting points for non-technical users before deeper agent-led customisation.',
      fields: [
        {
          type: 'string',
          name: 'width',
          label: 'Page Width',
          options: layoutWidthOptions,
          required: true,
        },
        {
          type: 'string',
          name: 'spacing',
          label: 'Section Spacing',
          options: layoutSpacingOptions,
          required: true,
        },
        {
          type: 'string',
          name: 'corners',
          label: 'Corner Style',
          options: layoutCornerOptions,
          required: true,
        },
        {
          type: 'string',
          name: 'header_style',
          label: 'Header Style',
          options: headerStyleOptions,
          required: true,
        },
      ],
    },
  ],
};

export default siteSettingsCollection;
